// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlc

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertIssue = `-- name: UpsertIssue :batchexec
INSERT INTO github_issues (
    repository_id, number, github_id, title, state, author_login, label_names, assignee_logins,
    comment_count, is_pull_request, body, github_created_at, github_updated_at, github_closed_at, raw_payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (repository_id, number) DO UPDATE SET
    github_id         = EXCLUDED.github_id,
    title             = EXCLUDED.title,
    state             = EXCLUDED.state,
    author_login      = EXCLUDED.author_login,
    label_names       = EXCLUDED.label_names,
    assignee_logins   = EXCLUDED.assignee_logins,
    comment_count     = EXCLUDED.comment_count,
    is_pull_request   = EXCLUDED.is_pull_request,
    body              = EXCLUDED.body,
    github_created_at = EXCLUDED.github_created_at,
    github_updated_at = EXCLUDED.github_updated_at,
    github_closed_at  = EXCLUDED.github_closed_at,
    raw_payload       = EXCLUDED.raw_payload,
    last_mined_at     = now()
WHERE github_issues.github_updated_at <= EXCLUDED.github_updated_at
`

type UpsertIssueBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertIssueParams struct {
	RepositoryID    int64           `json:"repository_id"`
	Number          int32           `json:"number"`
	GithubID        int64           `json:"github_id"`
	Title           string          `json:"title"`
	State           string          `json:"state"`
	AuthorLogin     *string         `json:"author_login"`
	LabelNames      []string        `json:"label_names"`
	AssigneeLogins  []string        `json:"assignee_logins"`
	CommentCount    int32           `json:"comment_count"`
	IsPullRequest   bool            `json:"is_pull_request"`
	Body            *string         `json:"body"`
	GithubCreatedAt time.Time       `json:"github_created_at"`
	GithubUpdatedAt time.Time       `json:"github_updated_at"`
	GithubClosedAt  *time.Time      `json:"github_closed_at"`
	RawPayload      json.RawMessage `json:"raw_payload"`
}

// Never overwrite newer data with an older snapshot (pages can be fetched out of order).
func (q *Queries) UpsertIssue(ctx context.Context, arg []UpsertIssueParams) *UpsertIssueBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RepositoryID,
			a.Number,
			a.GithubID,
			a.Title,
			a.State,
			a.AuthorLogin,
			a.LabelNames,
			a.AssigneeLogins,
			a.CommentCount,
			a.IsPullRequest,
			a.Body,
			a.GithubCreatedAt,
			a.GithubUpdatedAt,
			a.GithubClosedAt,
			a.RawPayload,
		}
		batch.Queue(upsertIssue, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertIssueBatchResults{br, len(arg), false}
}

func (b *UpsertIssueBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertIssueBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
