// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlc

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertIssue = `-- name: UpsertIssue :batchexec
INSERT INTO github_issues (
    repository_id, number, github_id, title, state, author_login, labels, assignees,
    comments_count, is_pull_request, body, created_at, updated_at, closed_at, raw, mined_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, now())
ON CONFLICT (repository_id, number) DO UPDATE SET
    github_id       = EXCLUDED.github_id,
    title           = EXCLUDED.title,
    state           = EXCLUDED.state,
    author_login    = EXCLUDED.author_login,
    labels          = EXCLUDED.labels,
    assignees       = EXCLUDED.assignees,
    comments_count  = EXCLUDED.comments_count,
    is_pull_request = EXCLUDED.is_pull_request,
    body            = EXCLUDED.body,
    created_at      = EXCLUDED.created_at,
    updated_at      = EXCLUDED.updated_at,
    closed_at       = EXCLUDED.closed_at,
    raw             = EXCLUDED.raw,
    mined_at        = now()
WHERE github_issues.updated_at <= EXCLUDED.updated_at
`

type UpsertIssueBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertIssueParams struct {
	RepositoryID  int64           `json:"repository_id"`
	Number        int32           `json:"number"`
	GithubID      int64           `json:"github_id"`
	Title         string          `json:"title"`
	State         string          `json:"state"`
	AuthorLogin   *string         `json:"author_login"`
	Labels        []string        `json:"labels"`
	Assignees     []string        `json:"assignees"`
	CommentsCount int32           `json:"comments_count"`
	IsPullRequest bool            `json:"is_pull_request"`
	Body          *string         `json:"body"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	ClosedAt      *time.Time      `json:"closed_at"`
	Raw           json.RawMessage `json:"raw"`
}

func (q *Queries) UpsertIssue(ctx context.Context, arg []UpsertIssueParams) *UpsertIssueBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RepositoryID,
			a.Number,
			a.GithubID,
			a.Title,
			a.State,
			a.AuthorLogin,
			a.Labels,
			a.Assignees,
			a.CommentsCount,
			a.IsPullRequest,
			a.Body,
			a.CreatedAt,
			a.UpdatedAt,
			a.ClosedAt,
			a.Raw,
		}
		batch.Queue(upsertIssue, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertIssueBatchResults{br, len(arg), false}
}

func (b *UpsertIssueBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertIssueBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
