// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"time"
)

const listIssues = `-- name: ListIssues :many
SELECT repository_id, number, github_id, title, state, author_login, label_names, assignee_logins,
       comment_count, is_pull_request, github_created_at, github_updated_at, github_closed_at,
       first_mined_at, last_mined_at
FROM github_issues
WHERE repository_id = $1
  AND ($4::text IS NULL OR state = $4)
  AND ($5::boolean IS NULL OR is_pull_request = $5)
ORDER BY number DESC
LIMIT $2 OFFSET $3
`

type ListIssuesParams struct {
	RepositoryID  int64   `json:"repository_id"`
	Limit         int32   `json:"limit"`
	Offset        int32   `json:"offset"`
	State         *string `json:"state"`
	IsPullRequest *bool   `json:"is_pull_request"`
}

type ListIssuesRow struct {
	RepositoryID    int64      `json:"repository_id"`
	Number          int32      `json:"number"`
	GithubID        int64      `json:"github_id"`
	Title           string     `json:"title"`
	State           string     `json:"state"`
	AuthorLogin     *string    `json:"author_login"`
	LabelNames      []string   `json:"label_names"`
	AssigneeLogins  []string   `json:"assignee_logins"`
	CommentCount    int32      `json:"comment_count"`
	IsPullRequest   bool       `json:"is_pull_request"`
	GithubCreatedAt time.Time  `json:"github_created_at"`
	GithubUpdatedAt time.Time  `json:"github_updated_at"`
	GithubClosedAt  *time.Time `json:"github_closed_at"`
	FirstMinedAt    time.Time  `json:"first_mined_at"`
	LastMinedAt     time.Time  `json:"last_mined_at"`
}

func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]ListIssuesRow, error) {
	rows, err := q.db.Query(ctx, listIssues,
		arg.RepositoryID,
		arg.Limit,
		arg.Offset,
		arg.State,
		arg.IsPullRequest,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesRow
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.RepositoryID,
			&i.Number,
			&i.GithubID,
			&i.Title,
			&i.State,
			&i.AuthorLogin,
			&i.LabelNames,
			&i.AssigneeLogins,
			&i.CommentCount,
			&i.IsPullRequest,
			&i.GithubCreatedAt,
			&i.GithubUpdatedAt,
			&i.GithubClosedAt,
			&i.FirstMinedAt,
			&i.LastMinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
