// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"
)

type Collection struct {
	ID         int64           `json:"id"`
	Platform   string          `json:"platform"`
	Params     json.RawMessage `json:"params"`
	Status     string          `json:"status"`
	CreatedBy  *int64          `json:"created_by"`
	CreatedAt  time.Time       `json:"created_at"`
	FinishedAt *time.Time      `json:"finished_at"`
}
