// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const cancelCollection = `-- name: CancelCollection :execrows
UPDATE collections SET status = 'canceled', finished_at = now()
WHERE id = $1 AND status = 'running'
`

func (q *Queries) CancelCollection(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, cancelCollection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (platform, parameters, created_by)
VALUES ($1, $2, $3)
RETURNING id, platform, parameters, status, created_by, created_at, finished_at
`

type CreateCollectionParams struct {
	Platform   string          `json:"platform"`
	Parameters json.RawMessage `json:"parameters"`
	CreatedBy  *int64          `json:"created_by"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.Platform, arg.Parameters, arg.CreatedBy)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Parameters,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishSettledCollections = `-- name: FinishSettledCollections :execrows
WITH totals AS (
    SELECT c.id,
           c.created_at,
           coalesce(sum(p.jobs_expected), 0) AS jobs_expected,
           coalesce(sum(p.jobs_done), 0)     AS jobs_done,
           coalesce(sum(p.jobs_failed), 0)   AS jobs_failed
    FROM collections c
    LEFT JOIN collection_progress p ON p.collection_id = c.id
    WHERE c.status = 'running'
    GROUP BY c.id
)
UPDATE collections c
SET status      = CASE WHEN t.jobs_failed > 0 THEN 'partial' ELSE 'completed' END,
    finished_at = now()
FROM totals t
WHERE c.id = t.id
  AND ((t.jobs_expected > 0 AND t.jobs_done + t.jobs_failed >= t.jobs_expected)
       OR (t.jobs_expected = 0 AND t.created_at < now() - interval '1 minute'))
`

// Marks running collections whose jobs have all settled. Collections that never
// enqueued anything are finished after a grace period.
func (q *Queries) FinishSettledCollections(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, finishSettledCollections)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCollection = `-- name: GetCollection :one
SELECT c.id, c.platform, c.parameters, c.status, c.created_by, c.created_at, c.finished_at,
       coalesce(sum(p.jobs_expected), 0)::bigint AS jobs_expected,
       coalesce(sum(p.jobs_done), 0)::bigint     AS jobs_done,
       coalesce(sum(p.jobs_failed), 0)::bigint   AS jobs_failed
FROM collections c
LEFT JOIN collection_progress p ON p.collection_id = c.id
WHERE c.id = $1
GROUP BY c.id
`

type GetCollectionRow struct {
	ID           int64           `json:"id"`
	Platform     string          `json:"platform"`
	Parameters   json.RawMessage `json:"parameters"`
	Status       string          `json:"status"`
	CreatedBy    *int64          `json:"created_by"`
	CreatedAt    time.Time       `json:"created_at"`
	FinishedAt   *time.Time      `json:"finished_at"`
	JobsExpected int64           `json:"jobs_expected"`
	JobsDone     int64           `json:"jobs_done"`
	JobsFailed   int64           `json:"jobs_failed"`
}

func (q *Queries) GetCollection(ctx context.Context, id int64) (GetCollectionRow, error) {
	row := q.db.QueryRow(ctx, getCollection, id)
	var i GetCollectionRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Parameters,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.JobsExpected,
		&i.JobsDone,
		&i.JobsFailed,
	)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT c.id, c.platform, c.parameters, c.status, c.created_by, c.created_at, c.finished_at,
       coalesce(sum(p.jobs_expected), 0)::bigint AS jobs_expected,
       coalesce(sum(p.jobs_done), 0)::bigint     AS jobs_done,
       coalesce(sum(p.jobs_failed), 0)::bigint   AS jobs_failed
FROM collections c
LEFT JOIN collection_progress p ON p.collection_id = c.id
GROUP BY c.id
ORDER BY c.id DESC
LIMIT $1 OFFSET $2
`

type ListCollectionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCollectionsRow struct {
	ID           int64           `json:"id"`
	Platform     string          `json:"platform"`
	Parameters   json.RawMessage `json:"parameters"`
	Status       string          `json:"status"`
	CreatedBy    *int64          `json:"created_by"`
	CreatedAt    time.Time       `json:"created_at"`
	FinishedAt   *time.Time      `json:"finished_at"`
	JobsExpected int64           `json:"jobs_expected"`
	JobsDone     int64           `json:"jobs_done"`
	JobsFailed   int64           `json:"jobs_failed"`
}

func (q *Queries) ListCollections(ctx context.Context, arg ListCollectionsParams) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionsRow
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Parameters,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.JobsExpected,
			&i.JobsDone,
			&i.JobsFailed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
