// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const consumeQuota = `-- name: ConsumeQuota :exec
UPDATE credential_quota SET remaining = remaining - 1
WHERE credential_id = $1 AND scope = $2 AND remaining > 0 AND reset_at > now()
`

type ConsumeQuotaParams struct {
	CredentialID int64  `json:"credential_id"`
	Scope        string `json:"scope"`
}

// Optimistic local decrement; the next API response overwrites it with the real value.
func (q *Queries) ConsumeQuota(ctx context.Context, arg ConsumeQuotaParams) error {
	_, err := q.db.Exec(ctx, consumeQuota, arg.CredentialID, arg.Scope)
	return err
}

const countActiveCredentials = `-- name: CountActiveCredentials :one
SELECT count(*) FROM credentials
WHERE platform = $1 AND status = 'active' AND deleted_at IS NULL
`

func (q *Queries) CountActiveCredentials(ctx context.Context, platform string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCredentials, platform)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCredential = `-- name: GetCredential :one
SELECT id, platform, kind, label, public_fields, secret_hints, secret_ciphertext, secret_nonce, key_version, status, last_tested_at, last_test_result, created_by, created_at, deleted_at FROM credentials WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCredential(ctx context.Context, id int64) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Kind,
		&i.Label,
		&i.PublicFields,
		&i.SecretHints,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Status,
		&i.LastTestedAt,
		&i.LastTestResult,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :one
INSERT INTO credentials (
    platform, kind, label, public_fields, secret_hints,
    secret_ciphertext, secret_nonce, key_version, status,
    last_tested_at, last_test_result, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), $10, $11)
RETURNING id, platform, kind, label, public_fields, secret_hints, secret_ciphertext, secret_nonce, key_version, status, last_tested_at, last_test_result, created_by, created_at, deleted_at
`

type InsertCredentialParams struct {
	Platform         string          `json:"platform"`
	Kind             string          `json:"kind"`
	Label            string          `json:"label"`
	PublicFields     json.RawMessage `json:"public_fields"`
	SecretHints      json.RawMessage `json:"secret_hints"`
	SecretCiphertext []byte          `json:"secret_ciphertext"`
	SecretNonce      []byte          `json:"secret_nonce"`
	KeyVersion       int32           `json:"key_version"`
	Status           string          `json:"status"`
	LastTestResult   json.RawMessage `json:"last_test_result"`
	CreatedBy        *int64          `json:"created_by"`
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, insertCredential,
		arg.Platform,
		arg.Kind,
		arg.Label,
		arg.PublicFields,
		arg.SecretHints,
		arg.SecretCiphertext,
		arg.SecretNonce,
		arg.KeyVersion,
		arg.Status,
		arg.LastTestResult,
		arg.CreatedBy,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Kind,
		&i.Label,
		&i.PublicFields,
		&i.SecretHints,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Status,
		&i.LastTestedAt,
		&i.LastTestResult,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, platform, kind, label, public_fields, secret_hints, secret_ciphertext, secret_nonce, key_version, status, last_tested_at, last_test_result, created_by, created_at, deleted_at FROM credentials
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR platform = $1)
ORDER BY platform, id
`

func (q *Queries) ListCredentials(ctx context.Context, platform *string) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentials, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Kind,
			&i.Label,
			&i.PublicFields,
			&i.SecretHints,
			&i.SecretCiphertext,
			&i.SecretNonce,
			&i.KeyVersion,
			&i.Status,
			&i.LastTestedAt,
			&i.LastTestResult,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCredentialInvalid = `-- name: MarkCredentialInvalid :exec
UPDATE credentials
SET status = 'invalid', last_test_result = jsonb_build_object('ok', false, 'reason', $2::text)
WHERE id = $1 AND status = 'active'
`

type MarkCredentialInvalidParams struct {
	ID     int64  `json:"id"`
	Reason string `json:"reason"`
}

func (q *Queries) MarkCredentialInvalid(ctx context.Context, arg MarkCredentialInvalidParams) error {
	_, err := q.db.Exec(ctx, markCredentialInvalid, arg.ID, arg.Reason)
	return err
}

const nextQuotaReset = `-- name: NextQuotaReset :one
SELECT q.reset_at FROM credential_quota q
JOIN credentials c ON c.id = q.credential_id
WHERE c.platform = $1 AND q.scope = $2
  AND c.status = 'active' AND c.deleted_at IS NULL
  AND q.reset_at > now()
ORDER BY q.reset_at
LIMIT 1
`

type NextQuotaResetParams struct {
	Platform string `json:"platform"`
	Scope    string `json:"scope"`
}

func (q *Queries) NextQuotaReset(ctx context.Context, arg NextQuotaResetParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, nextQuotaReset, arg.Platform, arg.Scope)
	var reset_at time.Time
	err := row.Scan(&reset_at)
	return reset_at, err
}

const pickCredential = `-- name: PickCredential :one
SELECT c.id, c.platform, c.kind, c.label, c.public_fields, c.secret_hints, c.secret_ciphertext, c.secret_nonce, c.key_version, c.status, c.last_tested_at, c.last_test_result, c.created_by, c.created_at, c.deleted_at FROM credentials c
LEFT JOIN credential_quota q ON q.credential_id = c.id AND q.scope = $1
WHERE c.platform = $2
  AND c.status = 'active'
  AND c.deleted_at IS NULL
  AND (q.credential_id IS NULL OR q.remaining > 0 OR q.reset_at <= now())
ORDER BY CASE WHEN q.credential_id IS NULL OR q.reset_at <= now() THEN 2147483647 ELSE q.remaining END DESC,
         random()
LIMIT 1
`

type PickCredentialParams struct {
	Scope    string `json:"scope"`
	Platform string `json:"platform"`
}

// The active credential with the most remaining quota in the given scope.
// Credentials without known quota (never used) or whose window has reset are
// preferred; random() spreads load between equally good candidates.
func (q *Queries) PickCredential(ctx context.Context, arg PickCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, pickCredential, arg.Scope, arg.Platform)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Kind,
		&i.Label,
		&i.PublicFields,
		&i.SecretHints,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Status,
		&i.LastTestedAt,
		&i.LastTestResult,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const recordTestResult = `-- name: RecordTestResult :one
UPDATE credentials
SET status = $2, last_tested_at = now(), last_test_result = $3
WHERE id = $1
RETURNING id, platform, kind, label, public_fields, secret_hints, secret_ciphertext, secret_nonce, key_version, status, last_tested_at, last_test_result, created_by, created_at, deleted_at
`

type RecordTestResultParams struct {
	ID             int64           `json:"id"`
	Status         string          `json:"status"`
	LastTestResult json.RawMessage `json:"last_test_result"`
}

func (q *Queries) RecordTestResult(ctx context.Context, arg RecordTestResultParams) (Credential, error) {
	row := q.db.QueryRow(ctx, recordTestResult, arg.ID, arg.Status, arg.LastTestResult)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Kind,
		&i.Label,
		&i.PublicFields,
		&i.SecretHints,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Status,
		&i.LastTestedAt,
		&i.LastTestResult,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteCredential = `-- name: SoftDeleteCredential :execrows
UPDATE credentials SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCredential(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCredential, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertQuota = `-- name: UpsertQuota :exec
INSERT INTO credential_quota (credential_id, scope, quota_limit, remaining, reset_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (credential_id, scope) DO UPDATE SET
    quota_limit = EXCLUDED.quota_limit,
    remaining   = EXCLUDED.remaining,
    reset_at    = EXCLUDED.reset_at,
    updated_at  = now()
`

type UpsertQuotaParams struct {
	CredentialID int64     `json:"credential_id"`
	Scope        string    `json:"scope"`
	QuotaLimit   int32     `json:"quota_limit"`
	Remaining    int32     `json:"remaining"`
	ResetAt      time.Time `json:"reset_at"`
}

func (q *Queries) UpsertQuota(ctx context.Context, arg UpsertQuotaParams) error {
	_, err := q.db.Exec(ctx, upsertQuota,
		arg.CredentialID,
		arg.Scope,
		arg.QuotaLimit,
		arg.Remaining,
		arg.ResetAt,
	)
	return err
}
