// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
)

const addProgress = `-- name: AddProgress :exec
INSERT INTO collection_progress (collection_id, shard, expected, done, failed)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (collection_id, shard) DO UPDATE SET
    expected = collection_progress.expected + EXCLUDED.expected,
    done     = collection_progress.done + EXCLUDED.done,
    failed   = collection_progress.failed + EXCLUDED.failed
`

type AddProgressParams struct {
	CollectionID int64 `json:"collection_id"`
	Shard        int16 `json:"shard"`
	Expected     int64 `json:"expected"`
	Done         int64 `json:"done"`
	Failed       int64 `json:"failed"`
}

func (q *Queries) AddProgress(ctx context.Context, arg AddProgressParams) error {
	_, err := q.db.Exec(ctx, addProgress,
		arg.CollectionID,
		arg.Shard,
		arg.Expected,
		arg.Done,
		arg.Failed,
	)
	return err
}
