// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlc

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertCommit = `-- name: InsertCommit :batchexec
INSERT INTO commits (
    sha, parents, author_name, author_email, authored_at,
    committer_name, committer_email, committed_at, message,
    additions, deletions, files_changed
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (sha) DO NOTHING
`

type InsertCommitBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertCommitParams struct {
	Sha            string    `json:"sha"`
	Parents        []string  `json:"parents"`
	AuthorName     string    `json:"author_name"`
	AuthorEmail    string    `json:"author_email"`
	AuthoredAt     time.Time `json:"authored_at"`
	CommitterName  string    `json:"committer_name"`
	CommitterEmail string    `json:"committer_email"`
	CommittedAt    time.Time `json:"committed_at"`
	Message        string    `json:"message"`
	Additions      int32     `json:"additions"`
	Deletions      int32     `json:"deletions"`
	FilesChanged   int32     `json:"files_changed"`
}

func (q *Queries) InsertCommit(ctx context.Context, arg []InsertCommitParams) *InsertCommitBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Sha,
			a.Parents,
			a.AuthorName,
			a.AuthorEmail,
			a.AuthoredAt,
			a.CommitterName,
			a.CommitterEmail,
			a.CommittedAt,
			a.Message,
			a.Additions,
			a.Deletions,
			a.FilesChanged,
		}
		batch.Queue(insertCommit, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertCommitBatchResults{br, len(arg), false}
}

func (b *InsertCommitBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertCommitBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertCommitFile = `-- name: InsertCommitFile :batchexec
INSERT INTO commit_files (sha, path, old_path, status, similarity, additions, deletions)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (sha, path) DO NOTHING
`

type InsertCommitFileBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertCommitFileParams struct {
	Sha        string  `json:"sha"`
	Path       string  `json:"path"`
	OldPath    *string `json:"old_path"`
	Status     string  `json:"status"`
	Similarity *int32  `json:"similarity"`
	Additions  *int32  `json:"additions"`
	Deletions  *int32  `json:"deletions"`
}

func (q *Queries) InsertCommitFile(ctx context.Context, arg []InsertCommitFileParams) *InsertCommitFileBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Sha,
			a.Path,
			a.OldPath,
			a.Status,
			a.Similarity,
			a.Additions,
			a.Deletions,
		}
		batch.Queue(insertCommitFile, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertCommitFileBatchResults{br, len(arg), false}
}

func (b *InsertCommitFileBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertCommitFileBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
