// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Commit struct {
	Sha            string    `json:"sha"`
	Parents        []string  `json:"parents"`
	AuthorName     string    `json:"author_name"`
	AuthorEmail    string    `json:"author_email"`
	AuthoredAt     time.Time `json:"authored_at"`
	CommitterName  string    `json:"committer_name"`
	CommitterEmail string    `json:"committer_email"`
	CommittedAt    time.Time `json:"committed_at"`
	Message        string    `json:"message"`
	Additions      int32     `json:"additions"`
	Deletions      int32     `json:"deletions"`
	FilesChanged   int32     `json:"files_changed"`
	MinedAt        time.Time `json:"mined_at"`
}

type CommitFile struct {
	Sha        string  `json:"sha"`
	Path       string  `json:"path"`
	OldPath    *string `json:"old_path"`
	Status     string  `json:"status"`
	Similarity *int32  `json:"similarity"`
	Additions  *int32  `json:"additions"`
	Deletions  *int32  `json:"deletions"`
}

type Repository struct {
	ID             int64      `json:"id"`
	Url            string     `json:"url"`
	Host           string     `json:"host"`
	Path           string     `json:"path"`
	MirrorSyncedAt *time.Time `json:"mirror_synced_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type RepositoryRemote struct {
	RepositoryID int64  `json:"repository_id"`
	Platform     string `json:"platform"`
	Owner        string `json:"owner"`
	Name         string `json:"name"`
}
