// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Commit struct {
	Sha            string    `json:"sha"`
	ParentShas     []string  `json:"parent_shas"`
	AuthorName     string    `json:"author_name"`
	AuthorEmail    string    `json:"author_email"`
	AuthoredAt     time.Time `json:"authored_at"`
	CommitterName  string    `json:"committer_name"`
	CommitterEmail string    `json:"committer_email"`
	CommittedAt    time.Time `json:"committed_at"`
	Message        string    `json:"message"`
	LinesAdded     int32     `json:"lines_added"`
	LinesDeleted   int32     `json:"lines_deleted"`
	FilesChanged   int32     `json:"files_changed"`
	FirstMinedAt   time.Time `json:"first_mined_at"`
}

type CommitFile struct {
	Sha               string  `json:"sha"`
	Path              string  `json:"path"`
	PreviousPath      *string `json:"previous_path"`
	ChangeType        string  `json:"change_type"`
	SimilarityPercent *int32  `json:"similarity_percent"`
	LinesAdded        *int32  `json:"lines_added"`
	LinesDeleted      *int32  `json:"lines_deleted"`
}

type Repository struct {
	ID                 int64      `json:"id"`
	Url                string     `json:"url"`
	Host               string     `json:"host"`
	Path               string     `json:"path"`
	MirrorLastSyncedAt *time.Time `json:"mirror_last_synced_at"`
	CreatedAt          time.Time  `json:"created_at"`
}

type RepositoryRemote struct {
	RepositoryID int64  `json:"repository_id"`
	Platform     string `json:"platform"`
	Owner        string `json:"owner"`
	Name         string `json:"name"`
}
