// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
)

const deleteRefs = `-- name: DeleteRefs :exec
DELETE FROM refs WHERE repository_id = $1
`

func (q *Queries) DeleteRefs(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, deleteRefs, repositoryID)
	return err
}

const filterUnminedCommits = `-- name: FilterUnminedCommits :many
SELECT s.sha::text FROM unnest($1::text[]) AS s(sha)
WHERE NOT EXISTS (
    SELECT 1 FROM repository_commits rc
    WHERE rc.repository_id = $2 AND rc.sha = s.sha
)
`

type FilterUnminedCommitsParams struct {
	Shas         []string `json:"shas"`
	RepositoryID int64    `json:"repository_id"`
}

func (q *Queries) FilterUnminedCommits(ctx context.Context, arg FilterUnminedCommitsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filterUnminedCommits, arg.Shas, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var s_sha string
		if err := rows.Scan(&s_sha); err != nil {
			return nil, err
		}
		items = append(items, s_sha)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepository = `-- name: GetRepository :one
SELECT id, url, host, path, mirror_synced_at, created_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Host,
		&i.Path,
		&i.MirrorSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRepositoryCommit = `-- name: GetRepositoryCommit :one
SELECT c.sha, c.parents, c.author_name, c.author_email, c.authored_at, c.committer_name, c.committer_email, c.committed_at, c.message, c.additions, c.deletions, c.files_changed, c.mined_at FROM repository_commits rc
JOIN commits c ON c.sha = rc.sha
WHERE rc.repository_id = $1 AND rc.sha = $2
`

type GetRepositoryCommitParams struct {
	RepositoryID int64  `json:"repository_id"`
	Sha          string `json:"sha"`
}

func (q *Queries) GetRepositoryCommit(ctx context.Context, arg GetRepositoryCommitParams) (Commit, error) {
	row := q.db.QueryRow(ctx, getRepositoryCommit, arg.RepositoryID, arg.Sha)
	var i Commit
	err := row.Scan(
		&i.Sha,
		&i.Parents,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthoredAt,
		&i.CommitterName,
		&i.CommitterEmail,
		&i.CommittedAt,
		&i.Message,
		&i.Additions,
		&i.Deletions,
		&i.FilesChanged,
		&i.MinedAt,
	)
	return i, err
}

const insertRefs = `-- name: InsertRefs :exec
INSERT INTO refs (repository_id, name, sha)
SELECT $1, unnest($2::text[]), unnest($3::text[])
`

type InsertRefsParams struct {
	RepositoryID int64    `json:"repository_id"`
	Names        []string `json:"names"`
	Shas         []string `json:"shas"`
}

func (q *Queries) InsertRefs(ctx context.Context, arg InsertRefsParams) error {
	_, err := q.db.Exec(ctx, insertRefs, arg.RepositoryID, arg.Names, arg.Shas)
	return err
}

const linkCommits = `-- name: LinkCommits :exec
INSERT INTO repository_commits (repository_id, sha)
SELECT $1, unnest($2::text[])
ON CONFLICT DO NOTHING
`

type LinkCommitsParams struct {
	RepositoryID int64    `json:"repository_id"`
	Shas         []string `json:"shas"`
}

func (q *Queries) LinkCommits(ctx context.Context, arg LinkCommitsParams) error {
	_, err := q.db.Exec(ctx, linkCommits, arg.RepositoryID, arg.Shas)
	return err
}

const listCommitFiles = `-- name: ListCommitFiles :many
SELECT sha, path, old_path, status, similarity, additions, deletions FROM commit_files WHERE sha = $1 ORDER BY path
`

func (q *Queries) ListCommitFiles(ctx context.Context, sha string) ([]CommitFile, error) {
	rows, err := q.db.Query(ctx, listCommitFiles, sha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommitFile
	for rows.Next() {
		var i CommitFile
		if err := rows.Scan(
			&i.Sha,
			&i.Path,
			&i.OldPath,
			&i.Status,
			&i.Similarity,
			&i.Additions,
			&i.Deletions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommits = `-- name: ListCommits :many
SELECT c.sha, c.parents, c.author_name, c.author_email, c.authored_at, c.committer_name, c.committer_email, c.committed_at, c.message, c.additions, c.deletions, c.files_changed, c.mined_at FROM repository_commits rc
JOIN commits c ON c.sha = rc.sha
WHERE rc.repository_id = $1
ORDER BY c.committed_at DESC, c.sha
LIMIT $2 OFFSET $3
`

type ListCommitsParams struct {
	RepositoryID int64 `json:"repository_id"`
	Limit        int32 `json:"limit"`
	Offset       int32 `json:"offset"`
}

func (q *Queries) ListCommits(ctx context.Context, arg ListCommitsParams) ([]Commit, error) {
	rows, err := q.db.Query(ctx, listCommits, arg.RepositoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.Sha,
			&i.Parents,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthoredAt,
			&i.CommitterName,
			&i.CommitterEmail,
			&i.CommittedAt,
			&i.Message,
			&i.Additions,
			&i.Deletions,
			&i.FilesChanged,
			&i.MinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemotes = `-- name: ListRemotes :many
SELECT repository_id, platform, owner, name FROM repository_remotes WHERE repository_id = ANY($1::bigint[])
`

func (q *Queries) ListRemotes(ctx context.Context, repositoryIds []int64) ([]RepositoryRemote, error) {
	rows, err := q.db.Query(ctx, listRemotes, repositoryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryRemote
	for rows.Next() {
		var i RepositoryRemote
		if err := rows.Scan(
			&i.RepositoryID,
			&i.Platform,
			&i.Owner,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, url, host, path, mirror_synced_at, created_at FROM repositories ORDER BY id DESC LIMIT $1 OFFSET $2
`

type ListRepositoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRepositories(ctx context.Context, arg ListRepositoriesParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Host,
			&i.Path,
			&i.MirrorSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMirrorSynced = `-- name: MarkMirrorSynced :exec
UPDATE repositories SET mirror_synced_at = now() WHERE id = $1
`

func (q *Queries) MarkMirrorSynced(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markMirrorSynced, id)
	return err
}

const upsertRemote = `-- name: UpsertRemote :exec
INSERT INTO repository_remotes (repository_id, platform, owner, name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, platform) DO UPDATE SET owner = EXCLUDED.owner, name = EXCLUDED.name
`

type UpsertRemoteParams struct {
	RepositoryID int64  `json:"repository_id"`
	Platform     string `json:"platform"`
	Owner        string `json:"owner"`
	Name         string `json:"name"`
}

func (q *Queries) UpsertRemote(ctx context.Context, arg UpsertRemoteParams) error {
	_, err := q.db.Exec(ctx, upsertRemote,
		arg.RepositoryID,
		arg.Platform,
		arg.Owner,
		arg.Name,
	)
	return err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (url, host, path)
VALUES ($1, $2, $3)
ON CONFLICT (url) DO UPDATE SET url = EXCLUDED.url
RETURNING id, url, host, path, mirror_synced_at, created_at
`

type UpsertRepositoryParams struct {
	Url  string `json:"url"`
	Host string `json:"host"`
	Path string `json:"path"`
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepository, arg.Url, arg.Host, arg.Path)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Host,
		&i.Path,
		&i.MirrorSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}
